### ISSUE TITLE
Duplicate People possible

### ISSUE THREAD

**Issue by pragyanone** [Marmo/debitum#119]
As of now, one can add a Person that already exists.

Also, it would be better if while adding a new Person, a list of matching People appears as one types.
Related to #113

**Comment by Marmo** [comment]
Can you please re-check if both people created really have the same name? Here I get an error message when trying to save a new person with the name of an already existing one.

**Comment by pragyanone** [comment]
Oh, my bad.
Yes, it throws an error.

**Comment by Marmo** [comment]
As for the second part of your suggestion, I will not add a list of matching people while typing in the add-person-dialog, since the choice/need to create a *new* person was already identified by the user. So IMO here (in contrast to the add-transaction-dialog in #113) such a list is not needed?/helpful.
