### ISSUE TITLE
Add currency type

### ISSUE THREAD

**Issue by roshavagarga** [Marmo/debitum#19]
In Money, I'd like to have multiple options to fill in on my own up to 3 glyphs after a transaction (some currencies have a symbol, others can just use the 3-letter exchange rate abbreviations).

Example:
Loan 1 to Ben is 500.
Loan 2 to Ben is 750.
Loan 3 to Ben is 1000.

Loan 1 was in US Dollars.
Loan 2 was in Euros.
Loan 3 was in Pesos.

With the different worth that makes the loans differ in weight :)

Edit: This could be added to the Note, so it might be superfluous.

**Comment by Marmo** [comment]
Thanks again for your suggestion!

I probably wont' implement this as for this use case either the sums displayed in person list and on top of the money list don't make sense anymore OR one would have to maintain exchange rates, too.

So that is another thing that is kind of possible using the description but won't have a specialized function in Debitum.
