### ISSUE TITLE
Add interest

### ISSUE THREAD

**Issue by roshavagarga** [Marmo/debitum#20]
Say I gave someone a loan and he hasn't returned it. I'd like to have the option to add a monthly or yearly interest rate to lent money, which would make it easier to account for inflation to boot.

Edit: Could be a flat percentage formula or it could look up stuff like the Consumer Price Index or something of the sort, if you can find an API, though that would add the 'Internet' flag requirement, so it should be something you can enable/disable.

**Comment by Marmo** [comment]
Thanks again for suggesting this :)

In the meantime (since you opened this issue) I added a note to the README that this is out of scope. I really want to keep things simple and for the needs of managing _personal_ debts and lent items, where (imho) generally no interests are used.

As always, one could add info about an interest rate to the description/note, but if that would be made use of rather often, I would recommend a more specialized app.
