### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [Marmo/debitum#72]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 1  warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on debitum (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure). 

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve debitum's security, and the quality of the reports of static analysis tools.
(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by Marmo** [comment]
I guess the warning is about debitum using MD5, right? This is not used for any cryptographic or security reason at all, so should be a false positive.
I use MD5 for deriving a number from a person's name String, so that I can derive a somehow random but fixed color for each name. So this is a purely cosmetic use of MD5, not trying to secure something.

If you still would like to share the gist with me, go ahead :) .

**Comment by misterAnderson90** [comment]
Hey Marmo,

Exac

**Comment by misterAnderson90** [comment]
Hello Marmo,

You are correct. The warning is related to the use of MD5. See the gist for more details: 

[Gist - MessageDigest](https://gist.github.com/misterAnderson90/64ef0b594d7e62c51278a082cab2cabb)

Thanks a lot for your response.
