### ISSUE TITLE
Quick guides shown in english even when translated

### ISSUE THREAD

**Issue by ferossan** [Marmo/debitum#83]
Corrections to the Spanish translation after 1.6.1 were not incorporated to 1.6.2. They should be in next version. The content of the "Quick Guide" is also already translated to Spanish, but still appears in English.

**Comment by Marmo** [comment]
Thanks for pointing me to the Quick Guide issue, this affects most of the translations. I just forgot some time ago, that I have to create a language specific value pointing to the translated file for every new language.

The changed spanish translations will be incorporated into the next release. Fyi: I did not include translations updates in 1.6.2 at all, since I fixed two really bad bugs and wanted to release these fixes asap.
