### ISSUE TITLE
New feature request: Allow "debt forgiveness"

### ISSUE THREAD

**Issue by luminous706** [Marmo/debitum#89]
Hello, I would like a way to "forgive" some amount, while stiil documenting it.

So maybe along with "Received", "Gave", there could be a third option: "Forgiven".

So I could put an amount to "forgive", it would reduce the total just like "gave", but it would be documented differently along with the other transactions.

**Comment by Marmo** [comment]
Thanks for your suggestion. I am sorry, but I will not add a third option "forgiven" among "gave" and "received", because this would erase the info of the original transaction's direction (was it my friend who gave me money and than forgave it or the other way round?).

So to me this is not a third option but two separate transactions, the second one rather "virtual", just a return transaction with a note indicating that the amount was forgiven.
