### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by mezysinc** [Marmo/debitum#9]

**Comment by mezysinc** [comment]
Few suggestions:

- Allow to add fotos when clicked on person's icons
- On MONEY TAB there is no MARK AS RETURNED option on edit (which is present in ITEMS TAB)
- in ITEMS TAB when you click on edit transaction and afterwards on RETURNED section, App crashes 
- Automatically HIDE AWAY virtual keyboard when clicked somewhere else on App
- On MONEY TAB there is no FILTER OPTION &
RETURNED DATE when edited

**Comment by Marmo** [comment]
Thank you for your suggestions (and pointing me to that crash; how could I miss this? I really have to create some tests I guess).

> Allow to add fotos when clicked on person's icons

This is something I already planned but that had a rather low priority for me (see [TODO.md](TODO.md)). I created #10 for this. 

> - On MONEY TAB there is no MARK AS RETURNED option on edit (which is present in ITEMS TAB)
> - On MONEY TAB there is no FILTER OPTION &
RETURNED DATE when edited

I think there is a fundamental difference in returning money vs. returning items, I wrote down my thoughts on this here: #3  (if you want some money back, just the sum has to be the same vs. you (typically) want exactly the same item back (not a dvd when you lent a book)). But since it indeed might be puzzling that the return option is missing, I think about adding a return option to the contextual action bar in the money list, that serves as a shortcut for creating a return transaction, see here #12.

> in ITEMS TAB when you click on edit transaction and afterwards on RETURNED section, App crashes

I fixed this in release 1.2.1. This still has to make its way into the F-Droid repo which typically takes about 2-3 days.

> Automatically HIDE AWAY virtual keyboard when clicked somewhere else on App

I am sorry but I don't understand what you mean, can you please elaborate on this?

**Comment by mezysinc** [comment]
- In case of 'returned money' option, interesting case would be if I lent $500 and on 15th someone gave back $180, 5 days later $200 and is still owing $120, just simply having option for history of debt

- Keyboard hide away (not sure if it's possible though), instead of using buttons from navigation bar of OS, force it to 'go away' by clicking somewhere else on App

- Make '+' button (when creating new transaction for items or money) more visible, alike orange/red? toggle switch button

**Comment by Marmo** [comment]
OK, I created #14 for the keyboard-thing.

As for the '+' Button I generally like that it is not that prominent, because it will be used rather seldom (once all persons are set up). So it should not stand out as much as the other controls IMO.

Yet I understand your point that it is a bit too much hidden, so I start experimenting with shape, size and color until I find a solution that is visible enough but does nit stand out too much and is visually appealing.

**Comment by Marmo** [comment]
So now let's discuss the return-money-issue (I don't want to convince you here, just exchange arguments to get close to an optimum solution).

> In case of 'returned money' option, interesting case would be if I lent $500 and on 15th someone gave back $180, 5 days later $200 and is still owing $120, just simply having option for history of debt

I think this can be easily achieved with the current logic:

Transactions in the scenario you described:
| Date | amount | direction | total |
|----|----|----|----|
| 2021-05-10 | $500 | user -> someone | $500 |
| 2021-05-15 | $180 | someone -> user | $320 |
| 2021-05-20 | $200 | someone -> user | $120 |

The history laid out in the above table can be easily seen if you filter the money list for the person "someone" (clicking on them in the person list). The remaining debt of $120 will be shown in the totals header.

#### Now my two points against assigning repaid-money-transactions to the original transaction:
##### 1 - transactions are harder to find

If the return transactions would be some history-entries of the first $500-Transaction (not ordinary transactions themselves), they would be harder to find imo (already wrote that somewhere in #3 ). If someone asked: I gave you $180 on 2021-05-15, do you remember? Did you take note of that? You now would just scroll to 2021-05-15 and see the $180-Transaction. If this repay-transaction would be part of the history of the $500-Transaction, you would have to scroll _there_ or use some date-search-function.

##### 2 - ambiguous attribution
Another point against assigning a transaction of returned money as a return-history-entry to an original transaction is the following:

Let's extend the scenario above with another transaction $200 user->someone on 2021-05-01:
| Date | amount | direction | total |
|----|----|----|----|
| 2021-05-01 | $200 | user -> someone | $200 |
| 2021-05-10 | $500 | user -> someone | $700 |
| 2021-05-15 | $180 | someone -> user | $520 |
| 2021-05-20 | $200 | someone -> user | $320 |

Would you attribute the repaid $180 (2021-5-15) to the $200- or the $500-Transaction? In the end it does not matter and you had to make a random choice. So imo it's better not to attribute it to any transaction at all, making it a "first-class" Transaction that contributes to the final sum like all other transactions. If (and I currently cannot imagine why) it is important to the user to note that these $180 are a nearly-complete-repay of the $200 from 2021-05-01 they can use the description field for this.

(this would start becoming important if we were talking about interests and contracts with deadlines, but that is beyond the scope of Debitum)

**Comment by mezysinc** [comment]
Yep, I'm all for implementing the compound interest together with little square for fingerprint input with automatic selfie to seal the mortgage loan...

just kidding ;)

You're explanation make total sense, just add entry that you received X amount from Y and see it through filter.
